# In order to activate Fusion Tables integration with OAuth 2.0 follow these steps:

#   *  Go to the Google API Console https://console.developers.google.com
#   *  If this is your first time using the Console, add a new project.
#   *  If you haven't done so already, turn on the Fusion Tables API (Enable API > Turn on Fusion Tables API)
#   *  Enter "APIs & auths > Credentials" on the left side and Create an OAuth 2.0 client ID.
#   *  Enter in your Product Name.
#   *  Keep the Web Application radio button selected, and enter the site or host name of your web application.
#   *  Click Create client ID.
#   *  Copy the client_id into api_key
#   *  Copy the client_sectet into the api_secret
#
# Restart your server in order to link your Google account

google:
  api_key: 628351364974-3qg7r00vk8e1glh3ek0rel89nesjgo4h.apps.googleusercontent.com
  api_secret: fQ_Sfs20c8ORWJvS-ron1Xbh
